// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'basicLayout': string;
  'basicLayoutContent': string;
}
export const cssExports: CssExports;
export default cssExports;
