// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appImg': string;
  'appLogo': string;
  'appName': string;
}
export const cssExports: CssExports;
export default cssExports;
