// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appName': string;
  'basicHeader': string;
  'basicHeaderLeft': string;
  'basicHeaderRight': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
