// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'noLogo': string;
  'siderMenu': string;
  'siderMenuHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
